GET http://localhost:5000/dosen


# router.get('/dosen', getDosen);
# router.get('/dosen/:id', getDosenById);
# router.post('/dosen', createDosen);
# router.patch('/dosen/:id', updateDosen);
# router.delete('/dosen/:id', deleteDosen);

### 
GET http://localhost:5000/dosen/1

### 
POST http://localhost:5000/dosen

Content-Type: application/json
{
"nip": "3456789012", 
"nidn": "98765432122",
"nama": "Dosen baru",
"no_whatsapp": "089657109999"
}

### 
PATCH   http://localhost:5000/dosen/1 
# Content-Type: application/json

# {
# "nip": "1234567890123456789", 
# "nidn": "98765432122",
# "nama": "Dosen baru",
# "no_whatsapp": "089657109999"
# }

###
DELETE http://localhost:5000/dosen/2