GET http://localhost:5000/admin

###
POST http://localhost:5000/login
Content-Type: application/json

{ 
    "username": "admin",
    "password" : "admin123"
}


###
DELETE http://localhost:5000/logout


###
GET http://localhost:5000/dosen

###

GET http://localhost:5000/admin

# router.get('/dosen', getDosen);
# router.get('/dosen/:id', getDosenById);
# router.post('/dosen', createDosen);
# router.patch('/dosen/:id', updateDosen);
# router.delete('/dosen/:id', deleteDosen);

### 
GET http://localhost:5000/dosen/1

### 
POST http://localhost:5000/dosen
Content-Type: application/json
{
"nip": "3456789012", 
"nidn": "98765432122",
"nama": "Dosen baru pisan",
"no_whatsapp": "089657109999"
}

### 
PATCH http://localhost:5000/dosen/7
Content-Type: application/json

{
"nip": "1234567890123456789", 
"nidn": "98765432122",
"nama": "Dosen baru",
"no_whatsapp": "089657109999"
}

###
DELETE http://localhost:5000/dosen/2

